"""empty message

Revision ID: 0263811719a1
Revises: e56f21fc4803
Create Date: 2019-09-03 23:40:50.347516

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0263811719a1'
down_revision = 'e56f21fc4803'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('agenda_slug', table_name='contact')
    op.drop_column('contact', 'agenda_slug')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contact', sa.Column('agenda_slug', mysql.VARCHAR(length=120), nullable=False))
    op.create_index('agenda_slug', 'contact', ['agenda_slug'], unique=True)
    # ### end Alembic commands ###
