"""empty message

Revision ID: e56f21fc4803
Revises: e6e003853b3e
Create Date: 2019-08-31 16:16:56.687911

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e56f21fc4803'
down_revision = 'e6e003853b3e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contact', sa.Column('agenda_slug', sa.String(length=120), nullable=False))
    op.create_unique_constraint(None, 'contact', ['agenda_slug'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'contact', type_='unique')
    op.drop_column('contact', 'agenda_slug')
    # ### end Alembic commands ###
